version: '3.8'

services:
  app:
    build: .
    container_name: mini-data-catalog-flask
    tty: true
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_catalog
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: